---
- assert:
    that: ansible_version.major == 2
    msg: "This playbook is for Ansible version 2"

- block:
    - include_vars: rhel-conf.yml

    - name: ensure epel repo is installed
      yum:
        name: epel-release
        state: present
      tags:
        - monit_install-packages

    - name: install monit
      yum:
        name: monit
        state: present
      tags:
        - monit_install-packages

    - name: create state/id directory
      file:
        path: "{{ monit_state_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      tags:
        - monit_create-packages-directories

    - name: create config directory
      file:
        path: "{{ monit_conf_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      tags:
        - monit_create-packages-directories

    - name: create control file
      template:
        src: monitrc.j2
        dest: "{{ monit_control_file }}"
        owner: root
        group: root
        mode: 0600
      notify:
        - restart monit
      tags:
        - monit_configure-control

    - name: enable monit in systemd
      service:
        name: monit
        enabled: yes
        state: started
      tags:
        - monit_configure-systemd-service

    - name: remove default logging configuration
      file:
        path: "{{ monit_conf_directory }}logging"
        state: absent
      tags:
        - monit_app-configs

    - name: Create configs
      template:
        src: "{{ item.type | default('base') }}.conf.j2"
        dest: "{{ monit_conf_directory }}{{ item.process | default(item.pid | basename | replace('.pid', '')) }}.conf"
        owner: root
        group: root
        mode: 0644
      with_flattened:
        - "{{ monit_process_list }}"
      when: item.pid is defined and item.pid
      notify:
        - restart monit
      tags:
        - monit_app-configs

    - name: add system monitor
      copy:
        src: system.conf
        dest: "{{ monit_conf_directory }}system.conf"
        owner: root
        group: root
        mode: 0644
      when:
        - monitor_system
      notify:
        - restart monit
      tags:
        - monit_app-configs

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- block:
    - include_vars: debian-conf.yml

    - name: install monit
      apt:
        name: monit
        state: present
      tags:
        - monit_install-packages

    - name: create state/id directory
      file:
        path: "{{ monit_state_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      tags:
        - monit_create-packages-directories

    - name: create config directory
      file:
        path: "{{ monit_conf_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      tags:
        - monit_create-packages-directories
        
    - name: create control file
      template:
        src: monitrc.j2
        dest: "{{ monit_control_file }}"
        owner: root
        group: root
        mode: 0600
      notify:
        - restart monit
      tags:
        - monit_configure-control

    - name: install monit systemd service file
      command: cp monit.service /lib/systemd/system/
      args:
        chdir: /usr/share/doc/monit/examples/
        creates: /lib/systemd/system/monit.service
      tags:
        - monit_systemd-service

    - name: enable monit in systemd
      service:
        name: monit
        enabled: yes
        state: started
      tags:
        - monit_systemd-service

    - name: reload systemctl if service file changed
      become: true
      command: systemctl daemon-reload
      when: ( servicefile|d() and servicefile.changed ) and ansible_distribution != 'Ubuntu'
      tags:
        - monit_systemd-service

    - block:
      - include_vars: debian-conf.yml
      - name: Create configs
        template:
          src: "{{ item.type | default('base') }}.conf.j2"
          dest: "{{ monit_conf_directory }}{{ item.process | default(item.pid | basename | replace('.pid', '')) }}.conf"
          owner: root
          group: root
          mode: 0644
        with_flattened:
          - "{{ monit_process_list }}"
        when: item.pid is defined and item.pid
        notify:
          - restart monit
        tags:
          - monit_app-configs
      when: ansible_distribution == 'Debian'

    - block:
      - include_vars: ubuntu-conf.yml
      - name: Create configs
        template:
          src: "{{ item.type | default('base') }}.conf.j2"
          dest: "/etc/monit/conf.d/{{ item.process | default(item.pid | basename | replace('.pid', '')) }}.conf"
          owner: root
          group: root
          mode: 0644
        with_flattened:
          - "{{ monit_process_list }}"
        when: item.pid is defined and item.pid
        notify:
          - restart monit
        tags:
          - monit_app-configs
      when: ansible_distribution == 'Ubuntu'

    - name: add system monitor
      copy:
        src: system.conf
        dest: "{{ monit_conf_directory }}system.conf"
        owner: root
        group: root
        mode: 0644
      when:
        - monitor_system
      notify:
        - restart monit
      tags:
        - monit_app-configs

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
